"""empty message

Revision ID: 4b1011f07cf2
Revises: 
Create Date: 2024-12-07 01:53:13.904887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b1011f07cf2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('age', sa.String(length=5), nullable=False),
    sa.Column('major', sa.String(length=10), nullable=False),
    sa.Column('mbti', sa.String(length=4), nullable=False),
    sa.Column('hobby', sa.String(length=25), nullable=True),
    sa.Column('contact', sa.String(length=25), nullable=False),
    sa.Column('image_data', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    # ### end Alembic commands ###
